### ISSUE TITLE
Abort if we fail to retrieve enclave image size?

### ISSUE THREAD

**Issue by roshanr95** [marlinprotocol/control-plane#5]
Should we just abort if we fail to fetch image size?

**Comment by nisarg-soni** [comment]
The only thing fetching image size is used for is to calculate the hdd to link to the instance and  in both cases the job remains open and the user gets charged. So if we don't abort there is a good possibility that the size is smaller and the everything might work perfectly but on the other hand if not it means an empty running instance until the `event` loop restarts and it retries everything including fetching image size. which might go through in the next try. So I think we should keep it going.
